name: CI
on: [push, pull_request]
jobs:
  build-and-test:
    name: 'Build & test / ${{ matrix.os }}'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: haskell-actions/setup@v2
      - run: cabal build all
      - run: cabal test all
